/*! Get the true bounding box size that fits a Windows 🖰mouse cursor=pointer using 2 methods:
  1. GetCursorInfo → GetIconInfo APIs that extracts nominal cursor size that is adjusted by screen DPI, but not adjusted for user accessibility multiplier, and them manually does the approximate adjustment for it. But does NOT take into account cursor shadow.
  2. DirectX duplication API that captures a screenshot and extracts mouse cursor from it. Takes into account all size-related factors: monitor scaling, user accessibility multiplier, cursor shadow.

  See win_api_const.ahk for an example on how to use in AutoHotkey
*/

use crate::libmod::ffi_api::std::mem;
use crate::libmod::*;


use widestring::WideChar;

use core::ffi::c_char;

use std	::{self,ptr};

use windows::Win32::UI::WindowsAndMessaging::{CURSORINFO,HCURSOR,CURSOR_SHOWING,};
use windows::Win32::UI::WindowsAndMessaging::GetCursorInfo;

use docpos::*;

#[unsafe(no_mangle)] pub extern "C"
fn get_mcursor_sz_ci(cur_box:&mut cur_box, coord:c_char, shadow:c_char) -> 𝑝𝑠 {
  // 1 🖰 Global cursor (GetCursorInfo) even if it's not owned by the current thread
  // 1.1 Get handle to the cursor itself
  let mut curℹ = CURSORINFO {cbSize: mem::size_of::<CURSORINFO>() as u32, ..Default::default()};
    /*hCursor:HCURSOR   cbSize:u32 (!must set before! ??? becomes 0 after GetCursorInfo call)
    flags      :CURSORINFO_FLAGS	0=hidden 1=CURSOR_SHOWING 2=CURSOR_SUPPRESSED (touch/pen)
    ptScreenPos:POINT           	screen coordinates of the cursor*/
  let res = unsafe { GetCursorInfo(&mut curℹ) }; if res.is_err()                 {*cur_box=cur_box::default(); return ffi𝑒("✗ Couldn't ‘GetCursorInfo’!"            )}
  let cur_h:HCURSOR = curℹ.hCursor;              if curℹ.flags != CURSOR_SHOWING {*cur_box=cur_box::default(); return ffi𝑒("✗ cursor is not shown (hidden or touch/pen)!")}

  // 1.2 Get/parse handle(s) to the cursor bitmap mask(s)
  let coords = parse_cursor_h(cur_h, false, &[], shadow != 0);
  match coords {
    Ok(mut c)	=> {if coord == Coord::Mon as i8 {cur_box_to_screen_hs(&mut c, &curℹ.ptScreenPos)}; *cur_box=c; ffi𝑒("")},
    Err(𝑒)   	=> {ffi𝑒(format!("✗ Couldn't get 🖰 cursor size box parsing bitmaps from ‘GetCursorInfo’ → ‘GetIconInfo’! 𝑒 = ‘{}’",𝑒))},
  }
}

#[unsafe(no_mangle)] pub extern "C"
fn get_mcursor_sz_dx(cur_box:&mut cur_box, coord:i8) -> 𝑝𝑠 {
  // 2 DXGI duplication API (screenshot the whole screen, get pointer image). Unlike ↑ captures shadow
  match get_mptr_sz(None, coord == Coord::Mon as i8, &[]) {
    Ok (c)	=> {*cur_box = c; ffi𝑒("")},
    Err(𝑒)	=> {              ffi𝑒(format!("{𝑒}"))},
  }
}

type 𝑝𝑠 = *mut WideChar;
use widestring::U16CString;

#[docpos]
fn ffi𝑒( /// Return an FFI-friendly error string to a non-Rust caller
  ///! Rust error string vallue to return. ❗ Must be deallocated via `dealloc_lib_string` to avoid memory leak (can't be deallocated by the caller)
  s: impl AsRef<str>,) -> 𝑝𝑠 { if s.as_ref().is_empty() {ptr::null_mut()} else {
    U16CString::from_str(s).map(U16CString::into_raw)
    .unwrap_or_else(|_𝑒|{// eprintln!("Error, `s` returned a string with inner null bytes: {}", 𝑒);
      ptr::null_mut()    }) //todo↑ print to win debug log
}}

/** # SAFETY
  Must be called only with a pointer generated by another Rust function via `.into_raw`. The pointer can't be used after this call, and the FFI receiver of this pointer can't edit it*/
#[unsafe(no_mangle)] pub unsafe extern "system"
fn dealloc_lib_string(𝑝:𝑝𝑠) {unsafe {
  if !𝑝.is_null() { drop::<U16CString>(U16CString::from_raw(𝑝)); }
}}
